full_name = "Oracle Linux 7"
short_name = "ol7"

[stigs]
[stigs.v2r1]
release_date = 2020-10-23
[stigs.v2r2]
release_date = 2021-01-22
[stigs.v2r3]
release_date = 2021-04-23
[stigs.v2r4]
release_date = 2021-07-23
[stigs.v2r5]
release_date = 2021-10-27
[stigs.v2r6]
release_date = 2022-01-27
[stigs.v2r7]
release_date = 2022-04-27
[stigs.v2r8]
release_date = 2022-07-22
[stigs.v2r9]
release_date = 2022-10-21
[stigs.v2r10]
release_date = 2023-01-13
[stigs.v2r11]
release_date = 2023-04-24
[stigs.v2r12]
release_date = 2023-07-20
[stigs.v2r13]
release_date = 2023-10-23
[stigs.v2r14]
release_date = 2024-01-23
