full_name = "Microsoft Windows 10"
short_name = "win10"

[stigs]
[stigs.v2r8]
release_date = 2023-11-02
[stigs.v2r9]
release_date = 2024-05-02
[stigs.v3r1]
release_date = 2024-07-17
[stigs.v3r2]
release_date = 2024-10-16
[stigs.v3r3]
release_date = 2025-01-28
[stigs.v3r4]
release_date = 2025-04-07
[stigs.v3r5]
release_date = 2025-11-26
[stigs.v3r6]
release_date = 2026-01-23
