full_name = "Red Hat Ansible Automation Controller App Server"
short_name = "appc_as"
[stigs]
[stigs.v1r1]
release_date = 2023-04-10
[stigs.v1r2]
release_date = 2023-10-23
[stigs.v2r1]
release_date = 2024-07-17
[stigs.v2r2]
release_date = 2025-08-07
