full_name = "Red Hat OpenShift Container Platform"
short_name = "ocp"

[stigs]
[stigs.v1r1]
release_date = 2023-09-08
[stigs.v2r1]
release_date = 2024-10-23
[stigs.v2r2]
release_date = 2025-01-28
[stigs.v2r3]
release_date = 2025-08-07
