full_name = "macOS 15 - Sequoia"
short_name = "macos15"

[stigs]
[stigs.v1r1]
release_date = 2024-10-19
[stigs.v1r2]
release_date = 2025-01-28
[stigs.v1r3]
release_date = 2025-04-07
[stigs.v1r5]
release_date = 2025-11-26
[stigs.v1r6]
release_date = 2026-01-22
