full_name = "Red Hat Enterprise Linux 9"
short_name = "rhel9"

[stigs]
[stigs.v1r1]
release_date = 2023-10-11
[stigs.v1r2]
release_date = 2024-01-23
[stigs.v1r3]
release_date = 2024-04-23
[stigs.v2r1]
release_date = 2024-07-17
[stigs.v2r2]
release_date = 2024-10-23
[stigs.v2r3]
release_date = 2025-01-28
[stigs.v2r4]
release_date = 2025-04-07
[stigs.v2r5]
release_date = 2025-08-07
[stigs.v2r6]
release_date = 2025-11-26
[stigs.v2r7]
release_date = 2026-01-23
