full_name = "Microsoft Internet Information Services 10 - Server"
short_name = "iis10"

[stigs.v3r1]
release_date = 2024-07-17
[stigs.v3r2]
release_date = 2024-10-23
[stigs.v3r4]
release_date = 2025-08-07
[stigs.v3r5]
release_date = 2025-11-26
